name: maigret2
adopt-info: maigret2
summary: SOCMINT / Instagram
description: |
  Test Test Test

license: MIT

base: core20
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64

apps:
  maigret2:
    command: bin/maigret
    environment:
      LC_ALL: C.UTF-8
    plugs:
      - home
      - network
      
parts:
  maigret2:
    plugin: python
    source: https://github.com/soxoj/maigret
    source-type: git
    
    build-packages:
      - python3-pip
      - python3-six
      - python3
      
    stage-packages:
      - python3
      - python3-six

    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"
